baseurl = "http://felixhanley.info/"
languageCode = "en-au"
title = "Felix Hanley"
relativeURLs = true

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Felix Hanley"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[[menu.main]]
    name = "PDF Résumé"
    identifier = "resume"
    parent = "work"
    url = "http://src.userspace.com.au/felix/resume/plain/felix_hanley.pdf"
    weight = 15
