baseurl = "//felixhanley.info/"
languageCode = "en-au"
title = "Felix Hanley"
relativeURLs = true
sectionPagesMenu = "main"

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

[author]
name = "Felix Hanley"

[frontmatter]
lastmod = ["lastmod", "publishDate"]

[markup.goldmark.renderer]
unsafe= true

[permalinks]
posts = "/posts/:year/:month/:title/"
