---
description: Résumé of Felix Hanley
title-meta: Résumé of Felix Hanley
keywords: [programmer,software,engineer,applied cryptography,encryption,devops,go,golang,javascript,ruby,python,php,css,html,openbsd,freebsd,linux,node,asn1,ansible,postgresql]
author: Felix Hanley
papersize: a4
mainfont: DejaVuSerifCondensed
mainfontoptions: [ Scale=1 ]
colorlinks: yes
linestretch: 1
geometry: [ margin=1.5cm ]
